# Generated by Django 5.1.15 on 2026-07-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('PSYTRANCE', 'Psytrance'), ('HITECH', 'Hi-Tech'), ('TECHNO', 'Techno'), ('EDM', 'EDM'), ('MELODIC_TECHNO', 'Melodic Techno')], default='PSYTRANCE', max_length=30)),
                ('youtube_url', models.URLField(blank=True)),
                ('soundcloud_url', models.URLField(blank=True)),
                ('audio_file', models.FileField(blank=True, help_text='Optional direct audio upload', null=True, upload_to='tracks/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tracks/covers/')),
                ('duration', models.CharField(blank=True, help_text='e.g. 58:20', max_length=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-release_date'],
            },
        ),
    ]
