# Generated by Django 5.1.15 on 2026-07-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, max_length=120)),
                ('venue', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Tickets Available'), ('SELLING_FAST', 'Selling Fast'), ('SOLD_OUT', 'Sold Out')], default='AVAILABLE', max_length=20)),
                ('ticket_url', models.URLField(blank=True, help_text='External ticketing link, or leave blank to link to Shop event passes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
