# Generated by Django 5.1.15 on 2026-07-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('CLUB', 'Club Night'), ('FESTIVAL', 'Festival'), ('PRIVATE', 'Private Party'), ('CORPORATE', 'Corporate Event'), ('WEDDING', 'Wedding'), ('OTHER', 'Other')], default='CLUB', max_length=20)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('budget', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONFIRMED', 'Confirmed'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Enquiry',
                'verbose_name_plural': 'Booking Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
